import { reactive } from 'vue';

export const sections = [
  { title: "Dados Pessoais", steps: 2 },
  { title: "Informações do Perfil", steps: 1 },
  { title: "Endereço", steps: 1 },
  { title: "Histórico Educacional", steps: 1 },
];

export const initialFormData = reactive({
  email: "",
  nome_completo: "",
  nome_social: "",
  nome_mae: "",
  cpf: "",
  anexo_cpf: null,
  registro_geral: "",
  anexo_rg: null,
  nacionalidade: "",
  naturalidade: "",
  data_nascimento: "",
  telefone_celular: "",
  polo_ofertante: "",
  genero: "",
  estado_civil: "",
  cpf_cedula_estrangeira: 0,
  rg_cedula_estrangeira: 0,
  portador_necessidades_especiais: "",
  necessidade_especial: "",
  renda_per_capita: "",
  etnia: "",
  area: "",
  logradouro: "",
  cep: "",
  bairro: "",
  cidade: "",
  numero: "",
  estado: "",
  complemento: "",
  tipo_escola: "",
  nivel_escolaridade: "",
  anexo_historico_escolar: null,
});